image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build the rust project and run the devserver
    init: cd src-tauri && cargo build
    command: |
      yarn add -D @tauri-apps/cli
      yarn tauri dev